package com.threeamigos.common.util.implementations.injection.abstractclasses.multipleconcreteclasses;

public class MultipleConcreteClassesStandardClass extends MultipleConcreteClassesAbstractClass {
}
