package com.threeamigos.common.util.implementations.injection.interfaces.multiplenotannotatedimplementations;

public class MultipleNotAnnotatedImplementationsStandardImplementation1 implements MultipleNotAnnotatedImplementationsInterface {
}
