package com.threeamigos.common.util.implementations.injection.abstractclasses.multipleannotatedconcreteclasses;

public class MultipleAnnotatedConcreteClassesStandardClass extends MultipleAnnotatedConcreteClassesAbstractClass {
}
