package com.threeamigos.common.util.implementations.injection.abstractclasses.multiplenotannotatedconcreteclasses;

public class MultipleNotAnnotatedConcreteClass1 extends MultipleNotAnnotatedAbstractClass {
}
