package com.threeamigos.common.util.interfaces.messagehandler;

import org.jspecify.annotations.NonNull;

import java.util.function.Supplier;

/**
 * An interface used to handle debug messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link DebugMessageHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface SupplierDebugMessageHandler {

    /**
     * Handles a single debug message generated by a supplier.
     *
     * @param debugMessageSupplier a supplier for a debug message to show to the programmer
     */
    void handleDebugMessage(@NonNull Supplier<String> debugMessageSupplier);

}
